model_path:
  large: "mistral-7b-instruct-v0.1.Q4_K_S.gguf"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: {'max_new_tokens': 512, 'temperature': 0,'context_length': 4096, 'gpu_layers': -1}

chat_history_path: "chat_sessions"